In [2]:
import torch


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_lo

In [3]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3 ,requires_grad=True)
b = torch.randn(3, requires_grad=True)

In [4]:
z = (x @ w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [5]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x130835810>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x1105fad70>


In [6]:
loss.backward()
print(f"weights: {w.grad}")
print(f"bias: {b.grad}")

weights: tensor([[0.0116, 0.3294, 0.2315],
        [0.0116, 0.3294, 0.2315],
        [0.0116, 0.3294, 0.2315],
        [0.0116, 0.3294, 0.2315],
        [0.0116, 0.3294, 0.2315]])
bias: tensor([0.0116, 0.3294, 0.2315])


In [13]:
#practice 
#2. find gradient
x = torch.tensor(4.0, requires_grad=True)

y = x**2

In [14]:
y.backward()

In [15]:
x.grad

tensor(8.)

In [18]:
#3. chain rule
x = torch.tensor(2.0, requires_grad=True)

y1 = (3*x + 1)**2

In [20]:
y1.backward()

In [21]:
x.grad

tensor(42.)

In [23]:
#4. vector gradient
x = torch.tensor([1.0,2.0,4.0], requires_grad=True)

y2 = (x**2 + 2*x).sum()

In [24]:
y2.backward()

In [25]:
y2

tensor(35., grad_fn=<SumBackward0>)

In [26]:
x.grad

tensor([ 4.,  6., 10.])

In [27]:
#5. gradient accumulation
x = torch.tensor(2.0, requires_grad=True)

y3 = x**2

y3.backward()

print(x.grad)

y3 = x**2

y3.backward()

print(x.grad)

tensor(4.)
tensor(8.)


In [ ]:
x = torch.tensor(2.0, requires_grad=True)

y3 = x**2

y3.backward()

print(x.grad)

x.grad.zero_()  #makes the x = [0.0]

y3 = x**2

y3.backward()

print(x.grad)

tensor(4.)
tensor(4.)


In [30]:
# 6. tiny neural network

w = torch.tensor(1.0, requires_grad=True)

x = 4.0

target = 20.0

prediction = w*x

loss = (prediction - target)**2

In [31]:
loss

tensor(256., grad_fn=<PowBackward0>)

In [32]:
loss.backward()

In [34]:
loss.grad_fn

In [35]:
w.grad

tensor(-128.)

In [36]:
#7. multistep computational graph

x = torch.tensor(2.0, requires_grad=True)

a = x + 1
b = a**2
c = 2*b
d = c + 3

`x -> a = x+1 -> b = (x+1)**2 -> c = 2*((x+1)**2) -> d = 2*((x+1)**2)+3` 

In [37]:
d.backward()
x.grad

tensor(12.)

In [ ]:
#8. shapes+gradient

x = torch.randn(5,3, requires_grad=True)
y4 = (x**2).mean()

In [43]:
x

tensor([[-0.2461,  1.5881, -0.2303],
        [ 0.7244, -1.2964, -0.5928],
        [-0.0071,  0.5854,  0.2723],
        [ 0.4092, -0.0578, -0.9128],
        [ 0.4374,  1.6782,  0.5742]], requires_grad=True)

In [41]:
y4.backward()

In [54]:
x_new = x.grad
x_new

tensor([[-0.0328,  0.2118, -0.0307],
        [ 0.0966, -0.1729, -0.0790],
        [-0.0009,  0.0781,  0.0363],
        [ 0.0546, -0.0077, -0.1217],
        [ 0.0583,  0.2238,  0.0766]])