In [3]:
import torch


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_lo

In [4]:
from sklearn.datasets import make_classification

In [5]:
X, y = make_classification(
    n_samples=20,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [6]:
X.shape

(20, 2)

In [7]:
y.shape

(20,)

In [8]:
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)

In [9]:
X_tensor

tensor([[-0.2828, -1.4088],
        [ 0.9470,  0.5591],
        [ 1.1577,  0.4750],
        [ 1.9959,  0.7728],
        [ 0.0405,  1.3973],
        [ 1.4704, -0.8606],
        [-0.7074,  0.8922],
        [-1.4569, -0.0456],
        [ 0.6220,  2.3675],
        [-0.0154,  1.0926],
        [ 1.6113, -0.6568],
        [ 1.4545,  0.9135],
        [-0.2071,  1.3306],
        [ 1.9632, -0.7697],
        [-0.9640, -0.8299],
        [ 2.0757,  0.6601],
        [-0.6550, -0.8359],
        [-1.4257, -1.3137],
        [-0.8750, -0.1135],
        [ 1.2558, -0.3721]])

In [10]:
y_tensor

tensor([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [11]:
from torch.utils.data import Dataset, DataLoader

In [12]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [13]:
dataset = CustomDataset(X_tensor, y_tensor)

In [14]:
len(dataset)   # or dataset.__len__()

20

In [15]:
dataset[0]

(tensor([-0.2828, -1.4088]), tensor(0))

In [16]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [17]:
for batch_features, batch_labels in dataloader:
    print(batch_features, '\n',batch_labels)
    print("-"*50)

tensor([[ 1.4545,  0.9135],
        [-0.0154,  1.0926],
        [-0.6550, -0.8359],
        [-0.9640, -0.8299]]) 
 tensor([1, 1, 0, 0])
--------------------------------------------------
tensor([[ 0.6220,  2.3675],
        [ 0.9470,  0.5591],
        [-1.4257, -1.3137],
        [-0.7074,  0.8922]]) 
 tensor([0, 0, 0, 1])
--------------------------------------------------
tensor([[ 1.9632, -0.7697],
        [-0.2828, -1.4088],
        [ 1.6113, -0.6568],
        [ 1.1577,  0.4750]]) 
 tensor([0, 0, 0, 0])
--------------------------------------------------
tensor([[ 2.0757,  0.6601],
        [ 0.0405,  1.3973],
        [-0.2071,  1.3306],
        [ 1.2558, -0.3721]]) 
 tensor([1, 1, 1, 0])
--------------------------------------------------
tensor([[ 1.4704, -0.8606],
        [ 1.9959,  0.7728],
        [-0.8750, -0.1135],
        [-1.4569, -0.0456]]) 
 tensor([0, 1, 1, 1])
--------------------------------------------------


In [23]:
class LinearModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_1 = torch.nn.Linear(2, 1)
        self.relu = torch.relu(self.layer_1())

    def forward(self, x):
        out = self.relu(self.layer_1(x))

        return out

In [25]:
model_linear = LinearModel()
model_linear.forward(X_tensor)

TypeError: Linear.forward() missing 1 required positional argument: 'input'

In [19]:
# for epoch in range(100):
#     for batch_features, batch_labels in dataloader:
        