In [1]:
!pip3 install torch

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m pip install --upgrade pip


In [2]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/sanaurooj/Library/Python/3.12/lib/python/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_lo

2.2.2


# Intro to Tensors

In [3]:
#creating tensors
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#tensor to python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[1,2],
                       [3,4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([1, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0][1][2]

tensor(6)

In [17]:
#creating random tensors
TENSOR2 = torch.tensor([[[[[1,2,3],
                           [3,4,5],
                           [6,7,8]]]]])

In [18]:
TENSOR2.ndim

5

In [19]:
TENSOR2.shape
# no. of subsequent brackets inside the bracket under consideration

torch.Size([1, 1, 1, 3, 3])

In [20]:
TENSOR2[0][0][0][2][1]

tensor(7)

## Random Tensors

### Random tensors are important because the way many neural networks work is they start with random numbers and then update them to better represent the data

`Start with random numbers -> look at data -> update the number -> look at data -> update the number`

In [21]:
# create a random tensor of size of (3, 4)
RANDOM_TENSOR = torch.rand(3, 3, 4)
RANDOM_TENSOR

tensor([[[0.6363, 0.4639, 0.8561, 0.2561],
         [0.2191, 0.9869, 0.0988, 0.3327],
         [0.8003, 0.7520, 0.7338, 0.1959]],

        [[0.6202, 0.0357, 0.3411, 0.9389],
         [0.8964, 0.9595, 0.6718, 0.2616],
         [0.1943, 0.8980, 0.0869, 0.3048]],

        [[0.7664, 0.8190, 0.1162, 0.0504],
         [0.6696, 0.5165, 0.7018, 0.7417],
         [0.8431, 0.5039, 0.8447, 0.0867]]])

In [22]:
RANDOM_TENSOR.ndim

3

In [23]:
RANDOM_TENSOR.shape

torch.Size([3, 3, 4])

In [24]:
# creating a random tensor with the same shape as a image tensor
random_img_size_tensor = torch.rand(3, 224, 224)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.shape, ones.ndim

(torch.Size([3, 4]), 2)

In [28]:
ones.dtype

torch.float32

In [29]:
ones * RANDOM_TENSOR

tensor([[[0.6363, 0.4639, 0.8561, 0.2561],
         [0.2191, 0.9869, 0.0988, 0.3327],
         [0.8003, 0.7520, 0.7338, 0.1959]],

        [[0.6202, 0.0357, 0.3411, 0.9389],
         [0.8964, 0.9595, 0.6718, 0.2616],
         [0.1943, 0.8980, 0.0869, 0.3048]],

        [[0.7664, 0.8190, 0.1162, 0.0504],
         [0.6696, 0.5165, 0.7018, 0.7417],
         [0.8431, 0.5039, 0.8447, 0.0867]]])

## Tensor-like

In [30]:
#use torch.arange() to create a tensor
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# use torch.zeros_like() to create a tensor of zeros of same shape as the input
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
# 30 practice problems
# 1
five_tensors = torch.tensor([1,2,3,4,5])
five_tensors

tensor([1, 2, 3, 4, 5])

In [ ]:
#2. 3*3 zero matrix
zero_matrix_order_three = torch.zeros(size=(3,3),dtype=int)
zero_matrix_order_three

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [39]:
#3. 4*4 one matrix
one_matrix_order_four = torch.ones(size=(4,4),dtype=int)
one_matrix_order_four

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [42]:
#4. tensor till 20
till_twenty = torch.arange(0,20)
till_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [43]:
#5. random tensor of shape(2,3)
random_tensor_size_two_by_three = torch.rand(size=(2,3))
random_tensor_size_two_by_three

tensor([[0.7636, 0.7636, 0.8692],
        [0.8249, 0.5243, 0.9866]])

In [45]:
#6. find shape, size, ndim
t = torch.tensor([[1,2,3],
     [4,5,6]])
print(f"shape: {t.shape}")
print(f"ndim: {t.ndim}")
print(f"numel: {t.numel()}")

shape: torch.Size([2, 3])
ndim: 2
numel: 6


In [50]:
#7. random tensor of shape(4,5,6)
t = torch.rand(size=(4,5,6))
print(f"shape: {t.shape}")
print(f"ndim: {t.ndim}\nnumel: {t.numel()}")

shape: torch.Size([4, 5, 6])
ndim: 3
numel: 120


In [53]:
#8. reshape
x = torch.arange(24)
x1 = torch.reshape(x, shape=(2,12))
x2 = torch.reshape(x, shape=(3, 8))
x3 = torch.reshape(x, shape=(4, 6))
print(f"x1: {x1}\nx2: {x2}\nx3: {x3}")

x1: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
x2: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
x3: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


In [55]:
#9. indexing
x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
x[1][1]

tensor(5)

In [56]:
#10. [4,5,6]
x[1]

tensor([4, 5, 6])

In [57]:
#11. [2,5,8]
x[:,1]

tensor([2, 5, 8])

In [59]:
#12. [[1,2],[4,5]]
x[:2,:2]

tensor([[1, 2],
        [4, 5]])

In [60]:
#13. negative indexing
x[-1]

tensor([7, 8, 9])

In [61]:
# tensor operations
#14. addition
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
x = a + b
x

tensor([5, 7, 9])

In [63]:
#15. element wise mul
x = a * b
x

tensor([ 4, 10, 18])

In [68]:
#16.a.sum(), a.mean(), a.max(), a.min()
print(f"sum: {a.sum()}")
print(f"mean: {int(a.sum()/len(a))}")
print(f"min: {a.min()}")
print(f"max: {a.max()}")

sum: 6
mean: 2
min: 1
max: 3


In [70]:
#17. index of maximum element
print(f"index: {a.argmax()}")

index: 2


## Matrix Operations

In [72]:
A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([
    [5,6],
    [7,8]
])

In [73]:
#18. A + B
A + B

tensor([[ 6,  8],
        [10, 12]])

In [74]:
#19. A * B
A * B

tensor([[ 5, 12],
        [21, 32]])

In [75]:
#20. matrix multiplication
A @ B

tensor([[19, 22],
        [43, 50]])

In [77]:
torch.matmul(A, B, out=A)

tensor([[ 19, 130],
        [ 43, 290]])

In [86]:
#21. transpose
torch.transpose(A, dim0=0,dim1=1)


tensor([[ 19,  43],
        [130, 290]])

## Reshaping

In [106]:
#22. covert to (3,4)
x = torch.arange(12)
x = x.reshape(shape=(3,4))

In [107]:
#23. flatten
x_flat = x.flatten()
x_flat


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
#24. (3,4) to (2,6)
x = x.reshape(shape=(2,6))

## Broadcasting

In [110]:
A = torch.tensor([
    [1,2,3],
    [4,5,6]
])

b = torch.tensor([10,20,30])

In [111]:
#25. add A and b
A + b

tensor([[11, 22, 33],
        [14, 25, 36]])

In [114]:
#26. multiply 5 to a tensor of 10 element
a = torch.arange(10)
5 * a

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

## Real D.L problems

In [119]:
#27. create 32 rgb images
rgb_images = torch.rand(size=(32,3,224,224))

In [120]:
rgb_images.shape

torch.Size([32, 3, 224, 224])

In [ ]:
#28. create labels
label = torch.randint(low=0, high=9, size=(1,32))
label

tensor([[6, 7, 1, 3, 1, 8, 6, 8, 0, 5, 8, 0, 3, 6, 7, 0, 7, 7, 2, 7, 4, 5, 5, 4,
         2, 6, 5, 4, 6, 2, 8, 3]])

In [132]:
#29. fake predictions
fake_pred = torch.randn(32,10)

In [133]:

fake_pred.argmax(dim=1)

tensor([7, 1, 4, 4, 5, 4, 9, 9, 3, 4, 8, 0, 4, 1, 5, 2, 2, 2, 6, 1, 5, 1, 8, 2,
        7, 7, 1, 2, 1, 0, 8, 4])